version: "3.9" # optional since v1.27.0
services:
  client:
    build: frontend
    ports:
      - "8085:80"
  #   depends_on:
  #     - server
  # server:
  #   build: backend
  #   ports:
  #     - "8084:8080"
